version: '3.8'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - '7432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  rbac_nestjs_app:
    build:
      context: .
      dockerfile: ./Dockerfile 
    ports:
      - '3000:3000' # Assuming Nest.js app runs on port 3000
    depends_on:
      - postgres


volumes:
  pgdata:
